name: Publish

on: workflow_dispatch

jobs:
  build-macos:
    runs-on: macos-11
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.1'

      - name: Checkout Books
        uses: actions/checkout@v2

      - name: Setup Books
        run: |
          yarn set version 1.22.18
          yarn

      - name: Run build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          yarn set version 1.22.18
          yarn electron:build --mac --publish never

      - name: Tar files
        run: tar -cvf dist-macOS.tar dist_electron

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-macOS
          path: dist-macOS.tar

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.1'

      - name: Checkout Books
        uses: actions/checkout@v2

      - name: Setup Books
        run: |
          yarn set version 1.22.18
          yarn

      - name: Run build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          yarn set version 1.22.18
          yarn electron:build --linux --publish never

      - name: Tar files
        run: tar -cvf dist-linux.tar dist_electron

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-linux
          path: dist-linux.tar

  build-windows:
    runs-on: windows-2019
    defaults:
      run:
        shell: bash

    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.1'

      - name: Checkout Books
        uses: actions/checkout@v2

      - name: Setup Books
        run: yarn

      - name: Run build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn electron:build --win --publish never

      - name: Tar files
        run: tar -cvf dist-windows.tar dist_electron

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-windows
          path: dist-windows.tar
