name: Test

on:
  push:
    branches: [$default-branch]
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  setup_and_test:
    runs-on: macos-11
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.1'

      - name: Set yarn version
        run: yarn set version 1.22.18

      - name: Checkout Books
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn

      - name: Yarn Tests
        run: yarn test